### ISSUE TITLE
Design Prototype

### ISSUE THREAD

**Issue by brandonhundt** [PRX/annual-report-2023#1]
produced in Figma, based on a style tile.

**Comment by kookster** [comment]
add labels to this project, and leave this for @brandonhundt 
probably a high, and idk the effort - 5? 8?

**Comment by cavis** [comment]
labels added

**Comment by brandonhundt** [comment]
Figma prototype complete. Indra is happy. Moving on to code. https://www.figma.com/file/g8NBo1y4aFpcKtstGKvYXM/2023-Annual-Report?type=design&node-id=385%3A7966&mode=design&t=XE2XANKfjJqGPLoT-1
